/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('./components/ui/Badge.vue')['default']
    Button: typeof import('./components/ui/Button.vue')['default']
    Card: typeof import('./components/ui/Card.vue')['default']
    CardContent: typeof import('./components/ui/CardContent.vue')['default']
    CardHeader: typeof import('./components/ui/CardHeader.vue')['default']
    CardTitle: typeof import('./components/ui/CardTitle.vue')['default']
    Input: typeof import('./components/ui/Input.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./components/ui/Select.vue')['default']
  }
}
